
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tgik.tgik.io
  resources:
  - squares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tgik.tgik.io
  resources:
  - squares/status
  verbs:
  - get
  - patch
  - update
