# permissions for end users to view squares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: square-viewer-role
rules:
- apiGroups:
  - tgik.tgik.io
  resources:
  - squares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tgik.tgik.io
  resources:
  - squares/status
  verbs:
  - get
